deployments:
  environmentMapping:
    development:
      - "develop"
      - "random"
      - "*-unstable"
    staging:
      - "new"
    testing:
      - "*-testing"
    production:
      - "*-stable"
