# This is a basic workflow to help you get started with Actions

name: My Deployment flow

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-dev1:
      runs-on: ubuntu-latest
      environment: dev*
      steps:
        - uses: actions/checkout@v3
          name: Create staging deployment
          id: deploy-to-dev1
          with:
            token: "${{ github.token }}"
            target_url: http://my-cool-app.com
            environment: development

  deploy-to-dev2:
      runs-on: ubuntu-latest
      environment: Entwicklung
      steps:
        - uses: actions/checkout@v3
          name: Create staging deployment
          id: deploy-to-dev2
          with:
            token: "${{ github.token }}"
            target_url: http://my-cool-app.com
            environment: development

  deploy-to-dev3:
      runs-on: ubuntu-latest
      environment: dev*
      steps:
        - uses: actions/checkout@v3
          name: desenvolvimento
          id: deploy-to-dev3
          with:
            token: "${{ github.token }}"
            target_url: http://my-cool-app.com
            environment: development

  deploy-to-staging1:
    runs-on: ubuntu-latest
    environment: Pre-Prod
    steps:
      - uses: actions/checkout@v3
        name: Create staging deployment
        id: deploy-to-staging1
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Staging

  deploy-to-staging2:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
        name: Create staging deployment
        id: deploy-to-staging2
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Staging

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: Produktion
    steps:
      - uses: actions/checkout@v3
        name: Create staging deployment
        id: deploy-to-prod
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com

  deploy-to-production:
    runs-on: ubuntu-latest
    environment: PROD-*
    steps:
      - uses: actions/checkout@v3
        name: Create staging deployment
        id: deploy-to-production
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: prod

