# This is a basic workflow to help you get started with Actions

name: My Deployment flow

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-dev:
      runs-on: ubuntu-latest
      environment: develop
      steps:
        - uses: actions/checkout@v3
          name: Create dev deployment
          id: deploy-to-dev
          with:
            token: "${{ github.token }}"
            target_url: http://my-cool-app.com
            environment: development
